### ISSUE TITLE
integration tests fail with "Invalid hostInfo"

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/koji-ansible#224]
We're hitting an error in `koji_call` in the integration test suite.

```
TASK [Add new builder1 host] ***************************************************
task path: /home/runner/work/koji-ansible/koji-ansible/tests/integration/koji_host/basic-1.yml:4
[... snip ...]
changed: [localhost] => changed=true 
  invocation:
    module_args:
      arches:
      - x86_64
      capacity: null
      channels:
      - createrepo
      - default
      comment: null
      description: null
      koji: null
      krb_principal: null
      krb_principals: null
      name: builder1.example.com
      state: enabled
  stdout_lines:
  - created host
  - added host to channel createrepo

TASK [koji_call] ***************************************************************
task path: /home/runner/work/koji-ansible/koji-ansible/tests/integration/koji_host/basic-1.yml:15
changed: [localhost] => changed=true 
  data:
    arches: x86_64
    capacity: 2.0
    comment: null
    description: null
    enabled: true
    id: 3
    name: builder1.example.com
    ready: false
    task_load: 0.0
    user_id: 4
  invocation:
    module_args:
      args:
      - builder1.example.com
      koji: null
      login: false
      name: getHost

TASK [assert] ******************************************************************
task path: /home/runner/work/koji-ansible/koji-ansible/tests/integration/koji_host/basic-1.yml:20
ok: [localhost] => changed=false 
  msg: All assertions passed

TASK [koji_call] ***************************************************************
task path: /home/runner/work/koji-ansible/koji-ansible/tests/integration/koji_host/basic-1.yml:30
The full traceback is:
Traceback (most recent call last):
  File "/home/runner/work/koji-ansible/koji-ansible/koji/koji/__init__.py", line 2756, in _callMethod
    return self._sendCall(handler, headers, request)
  File "/home/runner/work/koji-ansible/koji-ansible/koji/koji/__init__.py", line 2671, in _sendCall
    return self._sendOneCall(handler, headers, request)
  File "/home/runner/work/koji-ansible/koji-ansible/koji/koji/__init__.py", line 2720, in _sendOneCall
    ret = self._read_xmlrpc_response(r)
  File "/home/runner/work/koji-ansible/koji-ansible/koji/koji/__init__.py", line 2732, in _read_xmlrpc_response
    result = u.close()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1000: 'Invalid hostInfo: 3'>
```

**Comment by ktdreyer** [comment]
Last successful GitHub Actions environment:
```
ansible-4.1.0 ansible-core-2.11.1
python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
koji commit 3f0743a5e6e6d70d2eb053b2a3c8f1d20b65a180
```

Now failing GitHub Actions environment:
```
ansible-4.4.0 ansible-core-2.11.4
python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
koji commit ec70d21c41cac939d4236af4062ac20403ce5482
```

Looking through the changes to `kojihub.py`, [koji commit bc2a51350db2c40af31ed8a9f9a2bda834202d91](https://pagure.io/koji/c/bc2a51350db2c40af31ed8a9f9a2bda834202d91) included several changes to `list_channels()`, and this one stands out:

```diff
     if hostID:
+        if isinstance(hostID, str):
+            hostID = get_host(hostID, strict=True)['id']
```

`"Invalid hostInfo"` does come from `get_host()`.

**Comment by ktdreyer** [comment]
Prior to [koji commit bc2a51350](https://pagure.io/koji/c/bc2a51350db2c40af31ed8a9f9a2bda834202d91), it was possible to pass stringify'd ints, like so:

```python
# before bc2a51350, this would return the channels for the host id "1":
# after bc2a51350, this raises "Invalid hostInfo":
session.listChannels("1")
```

Now `listChannels` treats strings as hostnames.

```python
# before bc2a51350, this would raise a query error:
# after bc2a51350, it returns the channels for the hostname:
session.listChannels("builder1.example.com")
```
