### ISSUE TITLE
getAllPerms RPC crashes with psycopg2.ProgrammingError: column "description" does not exist

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/koji-ansible#262]
@meesha7 saw a new server-side crash recently in brew-stage. The RPC in `get_perms()` line 145 is `session.getAllPerms()`.

```
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1646915684.8-2166392567998/AnsiballZ_koji_tag.py", line 114, in <module>
    _ansiballz_main()
  File "/tmp/ansible-tmp-1646915684.8-2166392567998/AnsiballZ_koji_tag.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/ansible-tmp-1646915684.8-2166392567998/AnsiballZ_koji_tag.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/usr/lib64/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.9/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/tmp/ansible_koji_tag_payload_vlb33leq/__main__.py", line 821, in <module>
  File "/tmp/ansible_koji_tag_payload_vlb33leq/__main__.py", line 817, in main
  File "/tmp/ansible_koji_tag_payload_vlb33leq/__main__.py", line 797, in run_module
  File "/tmp/ansible_koji_tag_payload_vlb33leq/__main__.py", line 636, in ensure_tag
  File "/tmp/ansible_koji_tag_payload_vlb33leq/ansible_koji_tag_payload.zip/ansible_collections/ktdreyer/koji_ansible/plugins/module_utils/common_koji.py", line 151, in get_perm_id
  File "/tmp/ansible_koji_tag_payload_vlb33leq/ansible_koji_tag_payload.zip/ansible_collections/ktdreyer/koji_ansible/plugins/module_utils/common_koji.py", line 145, in get_perms
  File "/usr/lib/python3.9/site-packages/koji/__init__.py", line 2329, in __call__
    return self.__func(self.__name, args, opts)
  File "/usr/lib/python3.9/site-packages/koji/__init__.py", line 2775, in _callMethod
    raise err
  File "/usr/lib/python3.9/site-packages/koji/__init__.py", line 2756, in _callMethod
    return self._sendCall(handler, headers, request)
  File "/usr/lib/python3.9/site-packages/koji/__init__.py", line 2671, in _sendCall
    return self._sendOneCall(handler, headers, request)
  File "/usr/lib/python3.9/site-packages/koji/__init__.py", line 2720, in _sendOneCall
    ret = self._read_xmlrpc_response(r)
  File "/usr/lib/python3.9/site-packages/koji/__init__.py", line 2732, in _read_xmlrpc_response
    result = u.close()
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 662, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: '<class 'psycopg2.ProgrammingError'>: column "description" does not exist
LINE 1: SELECT id, name, description FROM permissions
```

**Comment by ktdreyer** [comment]
Reported upstream at https://pagure.io/koji/issue/3280

**Comment by ktdreyer** [comment]
It turned out the koji admins had not run the DB migration script in brew-stage. I cannot reproduce this independently in koji-ansible's CI, so it looks like it's resolved now.
